/// The shape the core hands over. Generated by hand today; when the
/// contract grows, it is generated from the Rust types so the two cannot
/// drift — see docs/ARCHITECTURE.md.
export type DecisionKind =
  | "Question"
  | "PlanApproval"
  | "Permission"
  | "Review"
  | "ScopeEscape"
  | "Stalled";

export interface QueueItem {
  session: string;
  kind: DecisionKind;
  raised_at: number;
  blocking: number;
  project_weight: number;
  /// The tool call that raised this decision, when one did. An id, and only
  /// an id — it is what lets the window look up what the decision says
  /// without the engine ever holding a word of it.
  raised_by: string | null;
  /// Which project this came from. Carried on the item rather than looked
  /// up: an item that cannot say where it belongs cannot be opened.
  project: string;
}

export interface Ranked {
  item: QueueItem;
  score: number;
  age_ms: number;
  kind_factor: number;
  weighted_age_ms: number;
  blocking_factor: number;
}

export interface Grouped {
  session: string;
  items: Ranked[];
}

export interface Wip {
  sessions_waiting: number;
  items: number;
  limit: number;
}

/// What a session is *about*, in words.
///
/// Read after the ranking is settled and merged in at the edge. The order
/// comes from metadata alone; this is what turns a row you must open into a
/// row you can triage.
export interface Glance {
  title: string | null;
  /// What each raised decision says, by the id that raised it.
  says: Record<string, string>;
  touched: number;
  unannounced: number;
}

export interface Queue {
  groups: Grouped[];
  wip: Wip;
  /// How many projects are being read. Distinguishes a quiet cockpit from an
  /// unconfigured one — two states that look identical on an empty screen.
  watching: number;
  /// Named rather than silent: a project the product could not read looks
  /// exactly like a project with nothing pending.
  unreachable: string[];
  /// One per session that has something waiting, by session id.
  glances: Record<string, Glance>;
  /// Set only when the configuration came from somewhere other than the
  /// default path. A cockpit pointed at a scratch configuration looks
  /// exactly like the real one, and the whole product is a claim about what
  /// needs you — so it has to say when the claim is about somewhere else.
  elsewhere: string | null;
}

/// How long something has been waiting, in the words a person uses.
export function age(ms: number): string {
  const m = Math.floor(ms / 60_000);
  if (m < 1) return "just now";
  if (m < 60) return `${m}min`;
  const h = Math.floor(m / 60);
  return h < 24 ? `${h}h${String(m % 60).padStart(2, "0")}` : `${Math.floor(h / 24)}d`;
}

/// What this row is, in as few words as it takes to decide whether to open it.
///
/// The kind alone makes you open the row to find out whether it matters, and
/// triage you cannot do without opening is not triage. Falls back to the kind
/// when there is nothing to add — an empty detail would be worse than none.
export function detail(r: Ranked, glance?: Glance): string | null {
  const said = r.item.raised_by ? glance?.says[r.item.raised_by] : undefined;
  if (said) return said;

  if (r.item.kind === "Review" && glance && glance.touched > 0) {
    const files = `${glance.touched} file${glance.touched === 1 ? "" : "s"} changed`;
    return glance.unannounced > 0 ? `${files} · ${glance.unannounced} unannounced` : files;
  }
  return null;
}

export function label(kind: DecisionKind): string {
  switch (kind) {
    case "Question":
      return "a question";
    case "PlanApproval":
      return "approve a plan";
    case "Permission":
      return "permission";
    case "Review":
      return "review";
    case "ScopeEscape":
      return "touched something outside scope";
    case "Stalled":
      return "stalled?";
  }
}
