[package]
name = "bancada-rules"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
bancada-meta = { workspace = true }
bancada-runtime = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
bancada-testing = { workspace = true }
