/// The shape the core hands over. Generated by hand today; when the
/// contract grows, it is generated from the Rust types so the two cannot
/// drift — see docs/ARCHITECTURE.md.
export type DecisionKind =
  | "Question"
  | "PlanApproval"
  | "Permission"
  | "Review"
  | "ScopeEscape"
  | "Stalled";

export interface QueueItem {
  session: string;
  kind: DecisionKind;
  raised_at: number;
  blocking: number;
  project_weight: number;
}

export interface Ranked {
  item: QueueItem;
  score: number;
  age_ms: number;
  kind_factor: number;
  weighted_age_ms: number;
  blocking_factor: number;
}

export interface Grouped {
  session: string;
  items: Ranked[];
}

export interface Wip {
  sessions_waiting: number;
  items: number;
  limit: number;
}

export interface Queue {
  groups: Grouped[];
  wip: Wip;
  /// How many projects are being read. Distinguishes a quiet cockpit from an
  /// unconfigured one — two states that look identical on an empty screen.
  watching: number;
  /// Named rather than silent: a project the product could not read looks
  /// exactly like a project with nothing pending.
  unreachable: string[];
}

/// How long something has been waiting, in the words a person uses.
export function age(ms: number): string {
  const m = Math.floor(ms / 60_000);
  if (m < 1) return "just now";
  if (m < 60) return `${m}min`;
  const h = Math.floor(m / 60);
  return h < 24 ? `${h}h${String(m % 60).padStart(2, "0")}` : `${Math.floor(h / 24)}d`;
}

export function label(kind: DecisionKind): string {
  switch (kind) {
    case "Question":
      return "a question";
    case "PlanApproval":
      return "approve a plan";
    case "Permission":
      return "permission";
    case "Review":
      return "review";
    case "ScopeEscape":
      return "touched something outside scope";
    case "Stalled":
      return "stalled?";
  }
}
