/// The product's mark, as an inline drawing.
///
/// Traced from `docs/logo/mark-light.svg`, which is generated by
/// `tools/logo.py`. Inline rather than an `<img>` because the whole reason
/// to use it here is to take the *page's* colour: an empty pane wants the
/// mark barely there, and an image file carries its own ink.
///
/// It follows `currentColor` for the same reason. Two tones would be the
/// logo; one is a watermark, which is what an empty pane is asking for.
export function Mark({ size = 96, className }: { size?: number; className?: string }) {
  return (
    <svg
      viewBox="0 0 64 64"
      width={size}
      height={size}
      fill="currentColor"
      aria-hidden="true"
      className={className}
    >
      <path d="M8.4 46.95 C20 46.25 42 46.15 55.8 46.65 L56.4 48.15 C42 48.75 20 48.85 8.2 48.45 Z" />
      <path d="M15.70 47.00 C15.80 43.00 19.34 23.57 21.43 11.84 Q23.50 11.00 25.57 11.16 C24.26 23.57 21.20 43.00 21.30 47.00 Z" />
      <path d="M28.05 47.00 C28.15 43.00 30.11 21.00 31.42 7.94 Q33.60 7.10 35.78 7.26 C35.33 21.00 33.85 43.00 33.95 47.00 Z" />
      <path d="M40.56 47.00 C40.66 43.00 43.94 22.45 45.93 10.14 Q48.10 9.30 50.27 9.46 C49.13 22.45 46.34 43.00 46.44 47.00 Z" />
    </svg>
  );
}
